name: professors_english_academy
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  velocity_x: ^4.3.1
  flutter_html: ^3.0.0
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  permission_handler: ^12.0.0+1
  device_info_plus: ^10.1.2
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  share_plus: ^10.1.4
  http: ^1.2.2
  get_storage: ^2.1.1
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.3
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  hold_to_confirm_button: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lang/

